# Generated by Django 3.0.3 on 2020-02-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maria', '0002_auto_20200213_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='NickName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='StudentID',
            field=models.CharField(max_length=20),
        ),
    ]
