# Generated by Django 3.0.3 on 2020-02-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maria', '0003_auto_20200213_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='NickName',
            field=models.TextField(max_length=30),
        ),
    ]
