# Generated by Django 3.0.3 on 2020-02-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maria', '0005_userphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphone',
            name='userphone',
            field=models.CharField(max_length=30),
        ),
    ]
