# Generated by Django 3.0.3 on 2020-02-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maria', '0006_auto_20200213_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userphone',
            old_name='userphone',
            new_name='UserPhone',
        ),
    ]
